[settings]
always_keep_download = false
always_keep_install = false
color = false
color_theme = "base16"
experimental = true
idiomatic_version_file_enable_tools = ["ruby"]
lockfile = true
disable_backends = ["asdf", "vfox"]

[tools]
"aqua:artempyanykh/marksman" = "latest"
"aqua:Automattic/harper/harper-ls" = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:charmbracelet/glow" = "latest"
"aqua:hadolint/hadolint" = "latest"
"aqua:ip7z/7zip" = "latest"
"aqua:jj-vcs/jj" = "latest"
"aqua:JohnnyMorganz/StyLua" = "latest"
"aqua:jqlang/jq" = "latest"
"aqua:Kitware/CMake" = "latest"
"aqua:koalaman/shellcheck" = "latest"
"aqua:LuaLS/lua-language-server" = "latest"
"aqua:mas-cli/mas" = "1.8.6"
"aqua:mattn/efm-langserver" = "latest"
"aqua:mgdm/htmlq" = "latest"
"aqua:mikefarah/yq" = "latest"
"aqua:mvdan/sh" = "latest"
"aqua:neovim/neovim" = "latest"
"aqua:pypa/pipx" = "latest"
"aqua:superfly/flyctl" = "latest"
"aqua:tree-sitter/tree-sitter" = "latest"
"aqua:watchexec/watchexec" = "latest"
"gem:create-ruby-app" = "latest"
"gem:nvim-context" = "latest"
"gem:tmuxinator" = "latest"
"github:cli/cli" = "latest"
"github:containers/podman" = "latest"
"github:elixir-lsp/elixir-ls" = { version = "latest", exe = "language_server.sh" }
"github:jgm/pandoc" = "latest"
"github:junegunn/fzf" = "latest"
"github:sharkdp/bat" = "latest"
"github:tekumara/typos-lsp" = "latest"
"github:tmux/tmux-builds" = "latest"
"github:wez/atomicparsley" = { version = "latest", asset_pattern = "AtomicParsleyMacOS.zip" }
"github:yt-dlp/yt-dlp" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:@sourcegraph/amp" = "latest"
"npm:@typescript/native-preview" = "7.0.0-dev.20260205.1"
"npm:alex" = "latest"
"npm:bash-language-server" = "latest"
"npm:diff-so-fancy" = "latest"
"npm:graphql-language-service-cli" = "latest"
"npm:trash-cli" = "latest"
"npm:typescript" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"pipx:yamllint" = "latest"
"ubi:atanunq/viu" = "latest"
"ubi:sst/opencode" = "latest"
bun = "latest"
erlang = "latest"
node = "24.10.0"
python = "latest"
ruby = "3.4.7"
rust = "latest"
yarn = "latest"
zig = "latest"
