[settings]
always_keep_download = false
always_keep_install = false
color = false
experimental = true
idiomatic_version_file_enable_tools = ["ruby"]
lockfile = true
disable_backends = ["asdf"]

[tools]
"aqua:mattn/efm-langserver" = "latest"
"aqua:watchexec/watchexec" = "latest"
"gem:bundler" = "latest"
"gem:create-ruby-app" = "latest"
"gem:pry" = "latest"
"gem:rubocop" = "latest"
"gem:rubocop-rspec" = "latest"
"gem:ruby-lsp" = "latest"
"gem:tmuxinator" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:bash-language-server" = "latest"
"npm:trash-cli" = "latest"
"npm:typescript-language-server" = "latest"
"npm:typescript" = "latest"
"npm:vscode-langservers-extracted" = "latest"
bat = "latest"
erlang = "latest"
flyctl = "latest"
fzf = "latest"
github-cli = "latest"
glow = "latest"
hadolint = "latest"
harper-ls = "latest"
htmlq = "latest"
jq = "latest"
lua-language-server = "latest"
marksman = "latest"
neovim = "latest"
node = "25.0.0"
python = "latest"
ripgrep = "latest"
ruby = "3.4.7"
rust = "latest"
shellcheck = "latest"
shfmt = "latest"
stylua = "latest"
tree-sitter = "latest"
yq = "latest"
