[settings]
always_keep_download = false
always_keep_install = false
color = false
experimental = true
idiomatic_version_file_enable_tools = ["ruby"]
lockfile = true
disable_backends = ["asdf", "vfox"]

[tools]
"aqua:artempyanykh/marksman" = "latest"
"aqua:Automattic/harper/harper-ls" = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:charmbracelet/glow" = "latest"
"aqua:cli/cli" = "latest"
"aqua:hadolint/hadolint" = "latest"
"aqua:jj-vcs/jj" = "latest"
"aqua:JohnnyMorganz/StyLua" = "latest"
"aqua:jqlang/jq" = "latest"
"aqua:Kitware/CMake" = "latest"
"aqua:koalaman/shellcheck" = "latest"
"aqua:LuaLS/lua-language-server" = "latest"
"aqua:mas-cli/mas" = "1.8.6"
"aqua:mattn/efm-langserver" = "latest"
"aqua:mgdm/htmlq" = "latest"
"aqua:mikefarah/yq" = "latest"
"aqua:mvdan/sh" = "latest"
"aqua:neovim/neovim" = "latest"
"aqua:pypa/pipx" = "latest"
"aqua:sharkdp/bat" = "latest"
"aqua:superfly/flyctl" = "latest"
"aqua:tree-sitter/tree-sitter" = "latest"
"aqua:watchexec/watchexec" = "latest"
"github:containers/podman" = "latest"
"github:jgm/pandoc" = "latest"
"github:junegunn/fzf" = "latest"
"github:tekumara/typos-lsp" = "latest"
"github:yt-dlp/yt-dlp" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@sourcegraph/amp" = "latest"
"npm:bash-language-server" = "latest"
"npm:trash-cli" = "latest"
"npm:typescript-language-server" = "latest"
"npm:typescript" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"pipx:yamllint" = "latest"
"ubi:sst/opencode" = "latest"
erlang = "latest"
node = "24.10.0"
python = "latest"
ruby = "3.4.7"
rust = "latest"
