[settings]
always_keep_download = false
always_keep_install = false
color = false
experimental = true
idiomatic_version_file_enable_tools = ["ruby"]
lockfile = true

[tools]
"aqua:mattn/efm-langserver" = "latest"
"aqua:watchexec/watchexec" = "latest"
"gem:bundler" = "latest"
"gem:rubocop" = "latest"
"gem:ruby-lsp" = "latest"
"gem:solargraph" = "latest"
"gem:tmuxinator" = "latest"
"npm:bash-language-server" = "latest"
"npm:trash-cli" = "latest"
"npm:typescript-language-server" = "latest"
"npm:typescript" = "latest"
"npm:vscode-langservers-extracted" = "latest"
bat = "latest"
flyctl = "latest"
fzf = "latest"
github-cli = "latest"
glow = "latest"
hadolint = "latest"
harper-ls = "latest"
htmlq = "latest"
jq = "latest"
lua-language-server = "latest"
marksman = "latest"
neovim = "latest"
node = "23.10.0"
python = "latest"
ripgrep = "latest"
rust = "latest"
shellcheck = "latest"
shfmt = "latest"
tree-sitter = "latest"
